server:
  port: 8080
  servlet:
    context-path: /sample-sp

logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: INFO
    org.opensaml.xmlsec: TRACE

spring:
  security:
    saml2:
      relyingparty:
        registration:
          samlexample:
            identityprovider:
              singlesignon:
                sign-request: false
              entity-id: https://samltest.id/saml/idp
              sso-url: https://samltest.id/idp/profile/SAML2/Redirect/SSO
              metadata-uri: https://samltest.id/saml/idp
